name = "Apollo"
uuid = "d07ff59c-5db4-4a8a-acb9-22af8761d4ca"
version = "0.0.1"
authors = ["Lachlan Whyborn lachlan.s.whyborn@gmail.com"]

[workspace]
projects = ["docs"]

[deps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
CommonDataModel = "0.4.2"
Dates = "1.11.0"
Debugger = "0.7.16"
Glob = "1.4.0"
NCDatasets = "0.14.10"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
